# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='protointerface',
  serialized_pb='\n\x0finterface.proto\x12\x0eprotointerface\"\x11\n\x0f\x46\x45\x43onfiguration\"2\n\x16TranslateConfiguration\x12\x18\n\rneighborCount\x18\x01 \x01(\r:\x01\x31\"?\n\x12MatchConfiguration\x12\x15\n\x08listSize\x18\x01 \x01(\r:\x03\x31\x30\x30\x12\x12\n\x08\x64\x61tabase\x18\x02 \x01(\t:\x00\"+\n\x12\x43\x61\x66\x66\x65\x43onfiguration\x12\x15\n\nresultSize\x18\x01 \x01(\r:\x01\x35\"1\n\x18\x43\x61\x66\x66\x65SearchConfiguration\x12\x15\n\nresultSize\x18\x01 \x01(\r:\x01\x35\"$\n\x13ResizeConfiguration\x12\r\n\x05ratio\x18\x01 \x01(\x01\"\xe0\x02\n\rConfiguration\x12\r\n\x05queue\x18\x01 \x01(\t\x12+\n\x02\x66\x65\x18\x02 \x01(\x0b\x32\x1f.protointerface.FEConfiguration\x12\x39\n\ttranslate\x18\x03 \x01(\x0b\x32&.protointerface.TranslateConfiguration\x12\x31\n\x05match\x18\x04 \x01(\x0b\x32\".protointerface.MatchConfiguration\x12\x31\n\x05\x63\x61\x66\x66\x65\x18\x05 \x01(\x0b\x32\".protointerface.CaffeConfiguration\x12=\n\x0b\x63\x61\x66\x66\x65Search\x18\x06 \x01(\x0b\x32(.protointerface.CaffeSearchConfiguration\x12\x33\n\x06resize\x18\x07 \x01(\x0b\x32#.protointerface.ResizeConfiguration\"*\n\tBlobFloat\x12\x0f\n\x03\x64im\x18\x01 \x03(\rB\x02\x10\x01\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\",\n\nResultList\x12\x11\n\x05score\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\x0b\n\x03url\x18\x02 \x03(\t\"\xbe\x02\n\x0bWorkRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x34\n\rconfiguration\x18\x03 \x03(\x0b\x32\x1d.protointerface.Configuration\x12\x38\n\x11pastConfiguration\x18\x05 \x03(\x0b\x32\x1d.protointerface.Configuration\x12\x14\n\terrorCode\x18\x06 \x01(\r:\x01\x30\x12\x0f\n\x07message\x18\x07 \x03(\t\x12\x13\n\x0breturnQueue\x18\x08 \x01(\t\x12\r\n\x05image\x18\x11 \x01(\x0c\x12\'\n\x04\x62lob\x18\x12 \x01(\x0b\x32\x19.protointerface.BlobFloat\x12*\n\x06result\x18\x13 \x01(\x0b\x32\x1a.protointerface.ResultList')




_FECONFIGURATION = _descriptor.Descriptor(
  name='FEConfiguration',
  full_name='protointerface.FEConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=52,
)


_TRANSLATECONFIGURATION = _descriptor.Descriptor(
  name='TranslateConfiguration',
  full_name='protointerface.TranslateConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neighborCount', full_name='protointerface.TranslateConfiguration.neighborCount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=104,
)


_MATCHCONFIGURATION = _descriptor.Descriptor(
  name='MatchConfiguration',
  full_name='protointerface.MatchConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='listSize', full_name='protointerface.MatchConfiguration.listSize', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database', full_name='protointerface.MatchConfiguration.database', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=106,
  serialized_end=169,
)


_CAFFECONFIGURATION = _descriptor.Descriptor(
  name='CaffeConfiguration',
  full_name='protointerface.CaffeConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='protointerface.CaffeConfiguration.resultSize', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=171,
  serialized_end=214,
)


_CAFFESEARCHCONFIGURATION = _descriptor.Descriptor(
  name='CaffeSearchConfiguration',
  full_name='protointerface.CaffeSearchConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultSize', full_name='protointerface.CaffeSearchConfiguration.resultSize', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=265,
)


_RESIZECONFIGURATION = _descriptor.Descriptor(
  name='ResizeConfiguration',
  full_name='protointerface.ResizeConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ratio', full_name='protointerface.ResizeConfiguration.ratio', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=267,
  serialized_end=303,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='protointerface.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue', full_name='protointerface.Configuration.queue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fe', full_name='protointerface.Configuration.fe', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='translate', full_name='protointerface.Configuration.translate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='match', full_name='protointerface.Configuration.match', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caffe', full_name='protointerface.Configuration.caffe', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caffeSearch', full_name='protointerface.Configuration.caffeSearch', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resize', full_name='protointerface.Configuration.resize', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=306,
  serialized_end=658,
)


_BLOBFLOAT = _descriptor.Descriptor(
  name='BlobFloat',
  full_name='protointerface.BlobFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='protointerface.BlobFloat.dim', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='data', full_name='protointerface.BlobFloat.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=660,
  serialized_end=702,
)


_RESULTLIST = _descriptor.Descriptor(
  name='ResultList',
  full_name='protointerface.ResultList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='protointerface.ResultList.score', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='url', full_name='protointerface.ResultList.url', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=704,
  serialized_end=748,
)


_WORKREQUEST = _descriptor.Descriptor(
  name='WorkRequest',
  full_name='protointerface.WorkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='protointerface.WorkRequest.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protointerface.WorkRequest.timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='configuration', full_name='protointerface.WorkRequest.configuration', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pastConfiguration', full_name='protointerface.WorkRequest.pastConfiguration', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='protointerface.WorkRequest.errorCode', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='protointerface.WorkRequest.message', index=5,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='returnQueue', full_name='protointerface.WorkRequest.returnQueue', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='protointerface.WorkRequest.image', index=7,
      number=17, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blob', full_name='protointerface.WorkRequest.blob', index=8,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='protointerface.WorkRequest.result', index=9,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=751,
  serialized_end=1069,
)

_CONFIGURATION.fields_by_name['fe'].message_type = _FECONFIGURATION
_CONFIGURATION.fields_by_name['translate'].message_type = _TRANSLATECONFIGURATION
_CONFIGURATION.fields_by_name['match'].message_type = _MATCHCONFIGURATION
_CONFIGURATION.fields_by_name['caffe'].message_type = _CAFFECONFIGURATION
_CONFIGURATION.fields_by_name['caffeSearch'].message_type = _CAFFESEARCHCONFIGURATION
_CONFIGURATION.fields_by_name['resize'].message_type = _RESIZECONFIGURATION
_WORKREQUEST.fields_by_name['configuration'].message_type = _CONFIGURATION
_WORKREQUEST.fields_by_name['pastConfiguration'].message_type = _CONFIGURATION
_WORKREQUEST.fields_by_name['blob'].message_type = _BLOBFLOAT
_WORKREQUEST.fields_by_name['result'].message_type = _RESULTLIST
DESCRIPTOR.message_types_by_name['FEConfiguration'] = _FECONFIGURATION
DESCRIPTOR.message_types_by_name['TranslateConfiguration'] = _TRANSLATECONFIGURATION
DESCRIPTOR.message_types_by_name['MatchConfiguration'] = _MATCHCONFIGURATION
DESCRIPTOR.message_types_by_name['CaffeConfiguration'] = _CAFFECONFIGURATION
DESCRIPTOR.message_types_by_name['CaffeSearchConfiguration'] = _CAFFESEARCHCONFIGURATION
DESCRIPTOR.message_types_by_name['ResizeConfiguration'] = _RESIZECONFIGURATION
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['BlobFloat'] = _BLOBFLOAT
DESCRIPTOR.message_types_by_name['ResultList'] = _RESULTLIST
DESCRIPTOR.message_types_by_name['WorkRequest'] = _WORKREQUEST

class FEConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FECONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.FEConfiguration)

class TranslateConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRANSLATECONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.TranslateConfiguration)

class MatchConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MATCHCONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.MatchConfiguration)

class CaffeConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAFFECONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.CaffeConfiguration)

class CaffeSearchConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAFFESEARCHCONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.CaffeSearchConfiguration)

class ResizeConfiguration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESIZECONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.ResizeConfiguration)

class Configuration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGURATION

  # @@protoc_insertion_point(class_scope:protointerface.Configuration)

class BlobFloat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOBFLOAT

  # @@protoc_insertion_point(class_scope:protointerface.BlobFloat)

class ResultList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESULTLIST

  # @@protoc_insertion_point(class_scope:protointerface.ResultList)

class WorkRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKREQUEST

  # @@protoc_insertion_point(class_scope:protointerface.WorkRequest)


_BLOBFLOAT.fields_by_name['dim'].has_options = True
_BLOBFLOAT.fields_by_name['dim']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_RESULTLIST.fields_by_name['score'].has_options = True
_RESULTLIST.fields_by_name['score']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
